"""
scripts/avax_usdc_deployer.py — Avalanche USDC Deployer

This script takes the output of the live gem scanner and the rebalance plan,
and automatically generates the execution parameters to deploy USDC into the
top-scoring AVAX gems via Trader Joe V2 or Pharaoh Exchange.

It acts as the bridge between discovery and execution. Once private keys are
loaded, the main bot loop will execute the trades generated by this script.
"""

import json
import os
import logging
from datetime import datetime, timezone

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-7s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("avax_deployer")

# ─────────────────────────────────────────────────────────────────────────────
# Config
# ─────────────────────────────────────────────────────────────────────────────
WALLET_B = "0x0835eb8447f3ac90351951bb5d22e77afd9b81c0"
USDC_AVAX = "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E"
WAVAX = "0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7"

MIN_SCORE_TO_DEPLOY = 75.0
MAX_POSITION_SIZE_USD = 35.0  # Max $35 per trade to manage risk
STANDARD_POSITION_SIZE_USD = 20.0

# ─────────────────────────────────────────────────────────────────────────────
# Main Deployer Logic
# ─────────────────────────────────────────────────────────────────────────────
def generate_deployment_plan():
    logger.info("Generating AVAX USDC deployment plan...")
    
    # 1. Load Rebalance Plan (to know how much USDC we have)
    try:
        with open("reports/avax_rebalance_plan.json", "r") as f:
            rebalance = json.load(f)
            usdc_balance = rebalance.get("capital", {}).get("usdc_balance", 0.0)
    except FileNotFoundError:
        logger.warning("No rebalance plan found. Assuming 0 USDC.")
        usdc_balance = 0.0

    # 2. Load latest scan results
    scan_files = [f for f in os.listdir("reports") if f.startswith("live_scan_")]
    if not scan_files:
        logger.error("No live scan reports found. Run live_scan_base_avax.py first.")
        return None
    
    latest_scan = sorted(scan_files)[-1]
    try:
        with open(f"reports/{latest_scan}", "r") as f:
            scan_data = json.load(f)
            avax_candidates = scan_data.get("results", {}).get("avalanche", [])
    except Exception as e:
        logger.error(f"Failed to load scan data: {e}")
        return None

    # 3. Filter for buy signals
    buy_signals = [c for c in avax_candidates if c.get("final_score", 0) >= MIN_SCORE_TO_DEPLOY]
    
    plan = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "wallet": WALLET_B,
        "available_usdc": usdc_balance,
        "trades": []
    }

    print("\n" + "=" * 80)
    print(f"  AVALANCHE USDC DEPLOYMENT PLAN")
    print("=" * 80)
    print(f"  Available USDC: ${usdc_balance:,.2f}")
    print(f"  Buy Signals Found: {len(buy_signals)}")
    print("-" * 80)

    if not buy_signals:
        print("  No gems met the minimum score threshold (≥75.0).")
        print("  Action: HOLD USDC. Wait for better setups.")
        print("=" * 80 + "\n")
        return plan

    # 4. Allocate capital
    remaining_usdc = usdc_balance
    for gem in buy_signals:
        if remaining_usdc < 5.0:
            logger.info("USDC depleted. Stopping allocation.")
            break
            
        score = gem["final_score"]
        
        # Determine size based on conviction
        if score >= 85.0:
            target_size = MAX_POSITION_SIZE_USD
            conviction = "HIGH (God Signal)"
        else:
            target_size = STANDARD_POSITION_SIZE_USD
            conviction = "STANDARD"
            
        # Cap at remaining balance
        actual_size = min(target_size, remaining_usdc)
        
        trade = {
            "token_in": USDC_AVAX,
            "token_in_symbol": "USDC",
            "token_out": gem["address"],
            "token_out_symbol": gem["symbol"],
            "amount_in_usd": actual_size,
            "conviction": conviction,
            "score": score,
            "router_preference": ["traderjoe", "pharaoh"],
            "slippage_bps": 300 if score >= 85 else 150  # Higher slippage for high conviction to ensure entry
        }
        
        plan["trades"].append(trade)
        remaining_usdc -= actual_size
        
        print(f"  🎯 TARGET: {gem['symbol']} ({gem['address'][:10]}...)")
        print(f"     Score:  {score:.1f}  [{conviction}]")
        print(f"     Action: Swap ${actual_size:.2f} USDC -> {gem['symbol']}")
        print(f"     Route:  Trader Joe V2 / Pharaoh (Slippage: {trade['slippage_bps']/100:.1f}%)")
        print()

    print("-" * 80)
    print(f"  Total USDC to Deploy: ${usdc_balance - remaining_usdc:.2f}")
    print(f"  Remaining USDC:       ${remaining_usdc:.2f}")
    print("=" * 80 + "\n")

    # Save deployment plan
    os.makedirs("reports", exist_ok=True)
    with open("reports/avax_deployment_plan.json", "w") as f:
        json.dump(plan, f, indent=2)
    logger.info("Deployment plan saved to reports/avax_deployment_plan.json")
    
    return plan

if __name__ == "__main__":
    generate_deployment_plan()
