"""
scripts/base_usdc_deployer.py — Base Chain USDC Deployer

This script takes the output of the live gem scanner and automatically generates 
the execution parameters to deploy the $1,321 USDC sitting in the Primary wallet 
on Base chain into top-scoring gems via Uniswap V3 or Aerodrome.

It acts as the bridge between discovery and execution. Once private keys are
loaded, the main bot loop will execute the trades generated by this script.
"""

import json
import os
import logging
from datetime import datetime, timezone

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-7s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("base_deployer")

# ─────────────────────────────────────────────────────────────────────────────
# Config
# ─────────────────────────────────────────────────────────────────────────────
PRIMARY_WALLET = "0x3eb320fad3f51fe4f2a4531f911ef56694346eef"
USDC_BASE = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
WETH_BASE = "0x4200000000000000000000000000000000000006"

MIN_SCORE_TO_DEPLOY = 75.0
MAX_POSITION_SIZE_USD = 150.0  # Max $150 per trade for high conviction
STANDARD_POSITION_SIZE_USD = 50.0 # Standard $50 snipe

# ─────────────────────────────────────────────────────────────────────────────
# Main Deployer Logic
# ─────────────────────────────────────────────────────────────────────────────
def generate_deployment_plan():
    logger.info("Generating Base USDC deployment plan...")
    
    # 1. We know we have ~$1321 USDC in Primary wallet on Base
    usdc_balance = 1321.0

    # 2. Load latest scan results
    scan_files = [f for f in os.listdir("reports") if f.startswith("live_scan_")]
    if not scan_files:
        logger.error("No live scan reports found. Run live_scan_base_avax.py first.")
        return None
    
    latest_scan = sorted(scan_files)[-1]
    try:
        with open(f"reports/{latest_scan}", "r") as f:
            scan_data = json.load(f)
            base_candidates = scan_data.get("results", {}).get("base", [])
    except Exception as e:
        logger.error(f"Failed to load scan data: {e}")
        return None

    # 3. Filter for buy signals
    buy_signals = [c for c in base_candidates if c.get("final_score", 0) >= MIN_SCORE_TO_DEPLOY]
    
    plan = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "wallet": PRIMARY_WALLET,
        "available_usdc": usdc_balance,
        "trades": []
    }

    print("\n" + "=" * 80)
    print(f"  BASE CHAIN USDC DEPLOYMENT PLAN")
    print("=" * 80)
    print(f"  Available USDC: ${usdc_balance:,.2f}")
    print(f"  Buy Signals Found: {len(buy_signals)}")
    print("-" * 80)

    if not buy_signals:
        print("  No gems met the minimum score threshold (≥75.0).")
        print("  Action: HOLD USDC. Wait for better setups.")
        print("=" * 80 + "\n")
        
        # Save empty plan
        os.makedirs("reports", exist_ok=True)
        with open("reports/base_deploy_plan.json", "w") as f:
            json.dump(plan, f, indent=2)
            
        return plan

    # 4. Allocate capital
    remaining_usdc = usdc_balance
    for gem in buy_signals:
        if remaining_usdc < 10.0:
            logger.info("USDC depleted. Stopping allocation.")
            break
            
        score = gem["final_score"]
        
        # Determine size based on conviction
        if score >= 85.0:
            target_size = MAX_POSITION_SIZE_USD
            conviction = "HIGH (God Signal)"
        else:
            target_size = STANDARD_POSITION_SIZE_USD
            conviction = "STANDARD"
            
        # Cap at remaining balance
        actual_size = min(target_size, remaining_usdc)
        
        trade = {
            "token_address": gem["address"],
            "token_symbol": gem["symbol"],
            "score": score,
            "conviction": conviction,
            "size_usdc": actual_size,
            "router": "aerodrome" if "aerodrome" in gem.get("dex", "").lower() else "uniswap_v3",
            "slippage_bps": 500 if score >= 85.0 else 300  # Higher slippage for high conviction snipes
        }
        
        plan["trades"].append(trade)
        remaining_usdc -= actual_size
        
        print(f"  [BUY] {gem['symbol']:<8} | Score: {score:.1f} | Size: ${actual_size:.2f} USDC | Router: {trade['router']}")

    print("-" * 80)
    print(f"  Total USDC to Deploy: ${usdc_balance - remaining_usdc:,.2f}")
    print(f"  Remaining USDC:       ${remaining_usdc:,.2f}")
    print("=" * 80 + "\n")

    # 5. Save plan
    os.makedirs("reports", exist_ok=True)
    with open("reports/base_deploy_plan.json", "w") as f:
        json.dump(plan, f, indent=2)
        
    logger.info("Deployment plan saved to reports/base_deploy_plan.json")
    return plan

if __name__ == "__main__":
    generate_deployment_plan()
